window.CMS_MODEL = {
  globals: [
    {
      id: "site-header",
      label: "页头",
      role: "全站页头组件",
      editable: ["Logo", "顶部工具链接", "主导航", "Mega 菜单", "手机端菜单", "联系按钮", "地区选择器"],
      storage: "/content/globals/header.json",
      template: "templates/global/header",
    },
    {
      id: "site-footer",
      label: "页脚",
      role: "全站页脚组件",
      editable: ["页脚 Logo", "订阅表单", "产品栏目", "支持链接", "下载链接", "关于链接"],
      storage: "/content/globals/footer.json",
      template: "templates/global/footer",
    },
    {
      id: "theme-style",
      label: "品牌样式",
      role: "全站 Logo、颜色、按钮、字体和圆角设置",
      editable: ["主色", "按钮颜色", "按钮文字颜色", "圆角", "字体族", "字号", "字重", "行高", "标题字号", "Google 翻译语言", "品牌 Logo"],
      storage: "/content/globals/theme.json",
      template: "templates/global/theme",
    },
    {
      id: "footer-cta",
      label: "底部 CTA",
      role: "全站复用行动号召模块",
      editable: ["背景图", "移动端背景图", "动态视频", "标题", "按钮文字", "按钮链接"],
      storage: "/content/globals/footer-cta.json",
      template: "templates/blocks/footer-cta",
    },
  ],
  collections: [
    {
      id: "products",
      label: "产品",
      directory: "/content/products/{category}/{product}.json",
      listTemplate: "templates/products/category-list",
      detailTemplate: "templates/products/detail",
      routePattern: "/products/{category}/{productId}",
      fields: ["标题", "分类", "路径", "首屏图", "摘要", "数据指标", "亮点", "图库", "下载", "SEO"],
    },
    {
      id: "product-categories",
      label: "产品分类",
      directory: "/content/product-categories/{category}.json",
      listTemplate: "templates/products/product-hub",
      detailTemplate: "templates/products/category-list",
      routePattern: "/products/{category}",
      fields: ["名称", "路径", "图标", "简介", "首屏媒体", "排序", "SEO"],
    },
    {
      id: "news",
      label: "新闻",
      directory: "/content/news/{article}.json",
      listTemplate: "templates/news/list",
      detailTemplate: "templates/news/detail",
      routePattern: "/news/{articleId}",
      fields: ["标题", "日期", "封面图", "摘要", "正文", "相关新闻", "SEO"],
    },
    {
      id: "pages",
      label: "页面",
      directory: "/content/pages/{page}.json",
      listTemplate: "templates/pages/default",
      detailTemplate: "templates/pages/default",
      routePattern: "/{page}",
      fields: ["标题", "路径", "首屏", "板块", "媒体", "SEO"],
    },
    {
      id: "downloads",
      label: "下载",
      directory: "/content/downloads/{type}/{file}.json",
      listTemplate: "templates/downloads/list",
      detailTemplate: "templates/downloads/file",
      routePattern: "/download/{type}",
      fields: ["文件标题", "关联产品", "下载类型", "PDF 文件", "版本", "发布状态"],
    },
  ],
  templates: [
    { id: "product-hub", label: "产品集合页模板", scope: "产品中心页面", file: "templates/products/product-hub", controls: ["首屏媒体", "分类网格", "系统板块", "CTA 模块"] },
    { id: "product-category", label: "产品分类/列表页模板", scope: "单个分类及产品卡片", file: "templates/products/category-list", controls: ["分类标签", "系列卡片", "下载板块", "排序"] },
    { id: "product-detail", label: "产品详情页模板", scope: "单个产品详情页", file: "templates/products/detail", controls: ["首屏布局", "数据指标", "优势卖点", "规格卡片", "资源链接"] },
    { id: "news-list", label: "新闻列表页模板", scope: "分页文章网格", file: "templates/news/list", controls: ["首屏", "文章卡片网格", "分页", "精选文章"] },
    { id: "news-detail", label: "新闻详情页模板", scope: "单篇文章页面", file: "templates/news/detail", controls: ["首屏图片", "发布信息", "富文本", "图片模块", "相关新闻"] },
    { id: "global-header", label: "页头模板", scope: "所有页面", file: "templates/global/header", controls: ["Logo", "菜单", "Mega 菜单布局", "联系 CTA", "移动端菜单"] },
    { id: "global-footer", label: "页脚模板", scope: "所有页面", file: "templates/global/footer", controls: ["栏目", "订阅表单", "社交链接", "法律链接"] },
    { id: "footer-cta", label: "底部 CTA 模板", scope: "全站复用 CTA 模块", file: "templates/blocks/footer-cta", controls: ["背景图", "动态视频", "标题", "按钮文字", "按钮链接"] },
    { id: "download-list", label: "下载中心模板", scope: "下载列表和筛选", file: "templates/downloads/list", controls: ["下载类型", "产品筛选", "文件卡片", "分页"] },
  ],
  assets: [
    { label: "产品图片", directory: "/uploads/products/", accepts: "jpg, png, webp" },
    { label: "新闻封面", directory: "/uploads/news/", accepts: "jpg, png, webp" },
    { label: "首屏媒体", directory: "/uploads/heroes/", accepts: "jpg, png, webp, mp4" },
    { label: "文档资料", directory: "/uploads/downloads/", accepts: "pdf, doc, xlsx" },
    { label: "品牌素材", directory: "/uploads/brand/", accepts: "svg, png, webp" },
  ],
  implementationPlan: [
    "前台模板与可编辑内容记录分开维护。",
    "产品、新闻、页面、下载、页头、页脚和全局样式统一保存为 JSON。",
    "Hostinger 上使用轻量 PHP 后台接口，支持登录、保存、上传和删除。",
    "前台网站读取 JSON 记录渲染，后续替换素材和文字不需要再改全局代码。",
  ],
};
